runtime: python27
api_version: 1
threadsafe: true

manual_scaling: 
  instances: 1

handlers:

- url: /(.*\.(css|eot|gz|html|ico|js|map|png|svg|ttf|woff|woff2))
  static_files: notdacodemanager/\1
  upload: notdacodemanager/(.*\.(css|eot|gz|html|ico|js|map|png|svg|ttf|woff|woff2))

- url: /.*
  static_files: notdacodemanager/index.html
  upload: notdacodemanager/index.html
  secure: always